In [1]:
import sudoku
import numpy as np

#### Sudoku game class test

In [12]:
a[(2,0)] = 3

In [13]:
#a = sudoku.sudoku_game(5, 10, 4)
#a.fill_diagonals()
print(a)

[[1 2 0 0]
 [4 3 0 0]
 [3 0 4 1]
 [0 0 2 3]]


In [11]:
loc = (2,0)
a.check_is_safe(loc, 2, verbose=True)

Number already in box:  True
Number already in row:  True
Number already in column:  True


False

#### Individual class test

In [2]:
individual = sudoku.individual()

In [3]:
individual.random_fill_board()

In [4]:
individual

[[3 1 8 4 2 9 2 2 2]
 [1 4 4 8 5 5 1 2 4]
 [3 8 6 5 7 2 1 1 1]
 [3 4 7 6 1 3 7 4 6]
 [9 8 3 7 4 5 8 1 5]
 [7 5 7 6 6 3 2 9 6]
 [8 3 6 6 8 7 1 5 9]
 [9 8 3 6 3 4 5 9 9]
 [7 9 9 5 2 4 2 8 7]]