In [1]:
import sudoku
import numpy as np

In [2]:
a = sudoku.sudoku_game(5, 10, 4)

In [3]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
a.fill_diagonals()

In [5]:
a

[[2 4 0 0]
 [1 3 0 0]
 [0 0 2 3]
 [0 0 1 4]]

In [8]:
a.check_unused_box((1,1), 1)

False