In [1]:
import sudoku
import numpy as np

#### Individual class test

In [26]:
board = best_neighbour.board
board[1:3, :] = 0
board

array([[6, 4, 2, 9, 5, 8, 3, 1, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 6, 3, 8, 9, 2, 7, 5, 1],
       [2, 8, 5, 1, 6, 7, 4, 9, 3],
       [7, 9, 1, 3, 4, 5, 8, 2, 6],
       [1, 3, 8, 5, 2, 9, 6, 7, 4],
       [5, 2, 6, 4, 7, 3, 1, 8, 9],
       [9, 7, 4, 6, 8, 1, 2, 3, 5]])

In [2]:
individual = sudoku.Individual()

In [3]:
individual

[[5 3 7 4 5 9 2 8 4]
 [8 6 7 1 7 4 2 8 9]
 [6 3 1 1 1 1 5 5 7]
 [2 3 7 3 2 8 8 5 6]
 [9 3 8 3 6 7 9 5 9]
 [8 9 4 7 6 5 9 2 9]
 [1 9 1 8 7 5 8 4 6]
 [3 3 5 2 4 2 4 2 1]
 [6 6 3 2 6 4 7 4 1]]

In [4]:
num_iterations = 10000
current_best = individual
best_fitness = current_best.fitness

for i in range(num_iterations):
    # Generate neighbours
    neighbours = current_best.get_neighbours(number_of_neighbours=1, swap_number=1)
    # Best fitness 
    neighbours_fitness = [neighbour.fitness for neighbour in neighbours]
    best_neighbour = neighbours[np.argmin(neighbours_fitness)]

    if best_neighbour.fitness <= best_fitness:
        print(f'Iteration {i} - New best fitness: {best_neighbour.fitness}')
        current_best = best_neighbour
        best_fitness = best_neighbour.fitness

    if best_fitness == 0:
        print(f'Solution found at iteration {i}')
        break

print(f'Best fitness: {best_fitness}')

Iteration 0 - New best fitness: 86
Iteration 1 - New best fitness: 85
Iteration 2 - New best fitness: 85
Iteration 3 - New best fitness: 85
Iteration 4 - New best fitness: 85
Iteration 5 - New best fitness: 85
Iteration 6 - New best fitness: 85
Iteration 7 - New best fitness: 82
Iteration 9 - New best fitness: 80
Iteration 14 - New best fitness: 77
Iteration 15 - New best fitness: 76
Iteration 16 - New best fitness: 76
Iteration 18 - New best fitness: 76
Iteration 19 - New best fitness: 76
Iteration 26 - New best fitness: 75
Iteration 28 - New best fitness: 74
Iteration 29 - New best fitness: 72
Iteration 30 - New best fitness: 72
Iteration 31 - New best fitness: 71
Iteration 33 - New best fitness: 70
Iteration 34 - New best fitness: 68
Iteration 35 - New best fitness: 68
Iteration 37 - New best fitness: 68
Iteration 38 - New best fitness: 65
Iteration 41 - New best fitness: 64
Iteration 43 - New best fitness: 64
Iteration 44 - New best fitness: 64
Iteration 46 - New best fitness: 62
I

In [10]:
best_neighbour

[[6 1 8 9 4 2 5 7 3]
 [5 4 7 3 6 1 2 9 8]
 [9 3 2 5 7 8 4 1 6]
 [4 2 1 6 8 9 3 5 7]
 [3 7 9 1 2 5 6 8 4]
 [8 5 6 4 3 7 9 2 1]
 [1 9 4 8 5 3 7 6 2]
 [2 6 5 7 1 4 8 3 9]
 [7 8 3 2 9 6 1 4 5]]