In [1]:
import sudoku
import numpy as np

#### Individual class test

In [16]:
individual = sudoku.individual()

In [17]:
individual.fitness

83

In [18]:
num_iterations = 10000
current_best = individual
best_fitness = current_best.fitness

for i in range(num_iterations):
    # Generate neighbours
    neighbours = current_best.get_neighbours(number_of_neighbours=10, swap_number=1)
    # Best fitness 
    neighbours_fitness = [neighbour.fitness for neighbour in neighbours]
    best_neighbour = neighbours[np.argmin(neighbours_fitness)]

    if best_neighbour.fitness <= best_fitness:
        print(f'Iteration {i} - New best fitness: {best_neighbour.fitness}')
        current_best = best_neighbour
        best_fitness = best_neighbour.fitness

    if best_fitness == 0:
        print(f'Solution found at iteration {i}')
        break

print(f'Best fitness: {best_fitness}')

Iteration 0 - New best fitness: 79
Iteration 1 - New best fitness: 76
Iteration 2 - New best fitness: 73
Iteration 3 - New best fitness: 70
Iteration 4 - New best fitness: 68
Iteration 5 - New best fitness: 64
Iteration 6 - New best fitness: 63
Iteration 7 - New best fitness: 62
Iteration 8 - New best fitness: 61
Iteration 9 - New best fitness: 57
Iteration 10 - New best fitness: 53
Iteration 11 - New best fitness: 51
Iteration 12 - New best fitness: 50
Iteration 13 - New best fitness: 48
Iteration 15 - New best fitness: 48
Iteration 16 - New best fitness: 48
Iteration 17 - New best fitness: 48
Iteration 18 - New best fitness: 48
Iteration 19 - New best fitness: 48
Iteration 20 - New best fitness: 47
Iteration 21 - New best fitness: 45
Iteration 22 - New best fitness: 45
Iteration 23 - New best fitness: 45
Iteration 24 - New best fitness: 44
Iteration 25 - New best fitness: 43
Iteration 26 - New best fitness: 43
Iteration 27 - New best fitness: 43
Iteration 28 - New best fitness: 43
It

In [20]:
best_neighbour

[[3 9 1 7 6 4 5 2 8]
 [4 5 6 2 8 9 1 3 7]
 [2 8 7 5 3 1 6 9 4]
 [1 2 8 9 4 6 3 7 5]
 [6 4 3 8 7 5 9 1 2]
 [5 7 9 1 2 3 8 4 6]
 [9 6 4 3 5 2 7 8 1]
 [7 3 2 6 1 8 4 5 9]
 [8 1 5 4 9 7 2 6 3]]

In [21]:
import turtle

# Funktion zum Zeichnen eines Quadrats
def draw_square(t, x, y, size, num):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.setheading(0)
    t.begin_fill()
    for _ in range(4):
        t.forward(size)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(x + size / 2, y - size / 4)
    t.write(num, align="center", font=("Arial", 12, "normal"))

# Funktion zum Zeichnen des Sudoku-Boards
def draw_sudoku(board):
    t = turtle.Turtle()
    t.speed(0)
    t.hideturtle()
    cell_size = 40
    x_start = -cell_size * 4
    y_start = cell_size * 4
    for i in range(9):
        for j in range(9):
            num = board[i][j]
            x = x_start + j * cell_size
            y = y_start - i * cell_size
            if num != 0:
                draw_square(t, x, y, cell_size, num)
    turtle.done()

In [22]:
draw_sudoku(best_neighbour.board)

Terminator: 