In [1]:
import Objects.sudoku as sudoku
import Objects.population as pop
import numpy as np

In [2]:
test_board = np.array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 0, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]])

In [3]:
population = pop.Population(
initial_board=test_board,
size=10
)

population.evolve(gens = 2,
                    xo_prob = 0.9 ,
                    mut_prob = 0.1, 
                    select_type='roulette', 
                    xo = 'single_point', 
                    elite_size= 10,
                    keep_distribution=True,
                    mutation='change', 
                    swap_number = 3, )

Perfect distribution [0 2 2 2 2 2 3 2 2 2]
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 -1  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0 -1]
 [ 0  1  1  0  0 -1 -1  0  0  0]
 [ 0  0  0 -1 -1  1  1 -1  0  1]
 [ 0 -1  0  1  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  1  0 -1  1]
 [ 0  0 -1 -1  1  0  1  0  0  0]
 [ 0  1 -1  0 -2  0  0  1  1  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
Iteration  1  Before  [8 7 2 2 3 4 5 8 3 9 9 1 6 3 7 5 4 6 6]
What to add [1]
What to remove [3]
Iteration  1  After  [8 7 2 2 3 4 5 8 3 9 9 1 6 1 7 5 4 6 6]
Iteration  2  Before  [8 7 2 2 3 4 5 8 3 9 9 9 1 6 7 5 4 6 6]
What to add [1]
What to remove [9]
Iteration  2  After  [8 7 2 2 3 4 5 8 3 9 9 1 1 6 7 5 4 6 6]
Iteration  3  Before  [6 2 7 5 6 1 4 8 6 3 8 9 5 4 3 6 9