In [1]:
import numpy as np 
from Algorithms.sudoku import Sudoku
from Algorithms.hill_climbing import HillClimbing
from Operators.fitness import fitness
from Operators.conflicts import box_conflicts

import time
import tqdm

In [6]:
# Lets do grid search to find the best parameters for the hill climbing algorithm
hill_climbing_args={'num_neighbours': np.arange(1, 10, 1), 
                    'swap_number': np.arange(1, 10, 1)}

num_iterations = 30
num_combinations = 10

means = {}
stds = {}
unable_args = []

for combination in tqdm.tqdm(range(num_combinations)):
    unable = False
    # Get the random parameters
    # arg_dictionnary = {'num_neighbours': np.random.choice(hill_climbing_args['num_neighbours']),
    #                     'swap_number': np.random.choice(hill_climbing_args['swap_number']), 
    #                     'max_iterations': 100000,
    #                     'plateau_threshold': 100
    #                     }

    arg_dictionnary = {'num_neighbours': combination+1,
                        'swap_number': 1, 
                        'max_iterations': 100000,
                        'plateau_threshold': 100,
                        'verbose': 2
                        }
    
    temp_results = []
    for iteration in range(num_iterations):
        if unable:
            break
        start = time.time()
        try:
            Sudoku(hill_climbing_args=arg_dictionnary)
        except:
            unable = True
            continue

        finish = time.time()
        temp_results.append(finish-start)
    
    if unable:
        print('Unable to solve the puzzle with arguments: ', arg_dictionnary)
        unable_args.append(arg_dictionnary)
        continue

    means[arg_dictionnary['num_neighbours'], arg_dictionnary['swap_number']] = np.mean(temp_results)
    stds[arg_dictionnary['num_neighbours'], arg_dictionnary['swap_number']] = np.std(temp_results)

  0%|          | 0/10 [00:00<?, ?it/s]

 10%|█         | 1/10 [00:17<02:36, 17.33s/it]

Found a solution in 23192 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 1, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 20%|██        | 2/10 [01:05<04:41, 35.19s/it]

Found a solution in 31776 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 2, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 30%|███       | 3/10 [01:28<03:27, 29.68s/it]

Found a solution in 10269 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 3, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 40%|████      | 4/10 [01:31<01:55, 19.20s/it]

Found a solution in 1048 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 4, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 50%|█████     | 5/10 [02:09<02:09, 25.94s/it]

Found a solution in 10058 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 5, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 60%|██████    | 6/10 [02:21<01:25, 21.38s/it]

Found a solution in 2758 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 6, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 70%|███████   | 7/10 [03:13<01:34, 31.42s/it]

Found a solution in 9807 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 7, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 80%|████████  | 8/10 [03:22<00:48, 24.26s/it]

Found a solution in 1480 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 8, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


 90%|█████████ | 9/10 [03:35<00:20, 20.77s/it]

Found a solution in 1921 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 9, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


100%|██████████| 10/10 [03:50<00:00, 23.07s/it]

Found a solution in 1950 iterations
Unable to solve the puzzle with arguments:  {'num_neighbours': 10, 'swap_number': 1, 'max_iterations': 100000, 'plateau_threshold': 100, 'verbose': 2}


In [5]:
new_individual = Sudoku(hill_climbing_args={'max_iterations' : 100000, 
                                            'verbose': 3, 
                                            'num_neighbours': 10})

Iter 0 : Found a better board with fitness 81
Iter 1 : Found a better board with fitness 78
Iter 2 : Found a better board with fitness 75
Iter 3 : Found a better board with fitness 73
Iter 4 : Found a better board with fitness 71
Iter 5 : Found a better board with fitness 69
Iter 6 : Found a better board with fitness 69
Iter 7 : Found a better board with fitness 67
Iter 8 : Found a better board with fitness 66
Iter 9 : Found a better board with fitness 65
Iter 10 : Found a better board with fitness 64
Iter 11 : Found a better board with fitness 64
Iter 12 : Found a better board with fitness 60
Iter 13 : Found a better board with fitness 58
Iter 14 : Found a better board with fitness 57
Iter 15 : Found a better board with fitness 57
Iter 16 : Found a better board with fitness 54
Iter 17 : Found a better board with fitness 52
Iter 18 : Found a better board with fitness 50
Iter 19 : Found a better board with fitness 50
Iter 20 : Found a better board with fitness 49
Iter 21 : Found a bette

TypeError: '>=' not supported between instances of 'NoneType' and 'int'

In [5]:
new_individual

[[5 3 4 7 6 2 8 1 9]
 [2 1 8 9 3 5 7 6 4]
 [9 7 6 4 8 1 5 2 3]
 [4 5 1 8 7 3 6 9 2]
 [7 6 2 1 4 9 3 8 5]
 [8 9 3 5 2 6 4 7 1]
 [6 2 5 3 9 7 1 4 8]
 [1 8 9 6 5 4 2 3 7]
 [3 4 7 2 1 8 9 5 6]]

In [2]:
board = np.array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 6, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]])
new_individual = Sudoku(initial_board=board)

In [19]:
climb = HillClimbing(new_individual.initial_board, new_individual.board)
climb.run(max_iterations=1000, swap_number=1, number_of_neighbours=1, verbose=True)

Iter 0 : Found a better board with fitness 25
Iter 3 : Found a better board with fitness 25
Iter 5 : Found a better board with fitness 23
Iter 6 : Found a better board with fitness 23
Iter 8 : Found a better board with fitness 21
Iter 10 : Found a better board with fitness 21
Iter 11 : Found a better board with fitness 21
Iter 12 : Found a better board with fitness 21
Iter 14 : Found a better board with fitness 18
Iter 15 : Found a better board with fitness 18
Iter 17 : Found a better board with fitness 18
Iter 18 : Found a better board with fitness 18
Iter 20 : Found a better board with fitness 18
Iter 21 : Found a better board with fitness 17
Iter 28 : Found a better board with fitness 17
Iter 30 : Found a better board with fitness 17
Iter 31 : Found a better board with fitness 15
Iter 36 : Found a better board with fitness 12
Iter 38 : Found a better board with fitness 12
Iter 39 : Found a better board with fitness 12
Iter 46 : Found a better board with fitness 12
Iter 47 : Found a 

In [11]:
climb.board

array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [8, 3, 1, 9, 4, 5, 6, 2, 7],
       [2, 5, 6, 1, 8, 7, 9, 4, 3],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 6, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]])

In [13]:
new_individual.display()


 3  6  7  |  1  6  3  |  9  2  9 
 4  4  2  |  9  3  9  |  4  9  1 
 3  3  8  |  8  2  7  |  3  8  8 
----------|-----------|----------
 8  7  7  |  5  5  2  |  3  1  2 
 5  7  6  |  7  7  1  |  4  1  9 
 1  5  8  |  1  5  2  |  8  2  3 
----------|-----------|----------
 2  6  6  |  7  9  6  |  7  7  4 
 3  5  6  |  9  4  4  |  2  5  6 
 9  8  2  |  1  3  3  |  3  8  1 
