In [1]:
import sudoku
import numpy as np

#### Individual class test

In [9]:
board = best_neighbour.board
board[1:3, :] = 0
board

array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 6, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]])

In [8]:
individual = sudoku.Individual(initial_board=np.array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 6, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]]))
individual 

[[9 4 7 3 2 6 5 8 1]
 [5 4 8 3 1 3 6 1 8]
 [7 2 7 9 5 2 6 9 4]
 [4 7 3 5 9 2 1 6 8]
 [1 2 9 8 6 4 7 3 5]
 [5 6 8 7 1 3 4 9 2]
 [7 9 2 4 5 8 3 1 6]
 [6 1 5 2 3 9 8 7 4]
 [3 8 4 6 7 1 2 5 9]]

In [10]:
test_board = np.array([[9, 4, 7, 3, 2, 6, 5, 8, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 7, 3, 5, 9, 2, 1, 6, 8],
       [1, 2, 9, 8, 6, 4, 7, 3, 5],
       [5, 6, 8, 7, 1, 3, 4, 9, 2],
       [7, 9, 2, 4, 5, 8, 3, 1, 6],
       [6, 1, 5, 2, 3, 9, 8, 7, 4],
       [3, 8, 4, 6, 7, 1, 2, 5, 9]])

In [13]:
population = sudoku.Population(
size=100,
initial_board=test_board
)

In [12]:
population.evolve(gens = 100,
                  xo_prob = 0.9, 
                  mut_prob=0.1, 
                  select_type='roulette', 
                  xo = 'single_point', 
                  mutate = True, #should be smth else
                  elitism = False)

(100, 81)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [4]:
[individual.fitness for individual in population.individuals]

AttributeError: 'numpy.ndarray' object has no attribute 'fitness'

In [5]:
population.individuals

[array([9, 4, 8, 5, 8, 1, 3, 9, 6, 7, 4, 9, 3, 2, 3, 9, 4, 2, 8, 1, 7, 1,
        2, 4, 5, 9, 3, 7, 8, 9, 4, 2, 9, 6, 6, 6, 6, 8, 1, 4, 5, 4, 2, 3,
        2, 5, 1, 6, 6, 4, 3, 8, 1, 1, 5, 8, 7, 5, 1, 7, 7, 5, 3, 9, 3, 7,
        2, 8, 5, 7, 3, 2, 2, 8, 6, 4, 1, 9, 5, 6, 7]),
 array([2, 5, 7, 6, 7, 2, 2, 7, 8, 4, 5, 1, 1, 5, 3, 1, 6, 4, 8, 6, 9, 4,
        5, 3, 3, 2, 4, 9, 8, 7, 1, 6, 9, 9, 9, 2, 1, 2, 3, 1, 4, 5, 3, 8,
        1, 2, 9, 1, 5, 7, 2, 1, 4, 2, 6, 8, 6, 8, 7, 4, 8, 4, 9, 9, 9, 7,
        7, 8, 7, 5, 6, 3, 6, 3, 3, 5, 8, 6, 3, 4, 5]),
 array([1, 1, 3, 1, 6, 7, 4, 7, 5, 8, 5, 9, 5, 6, 3, 8, 9, 5, 3, 4, 6, 2,
        1, 6, 2, 7, 3, 6, 3, 9, 1, 5, 2, 6, 3, 9, 8, 9, 7, 2, 9, 7, 6, 8,
        7, 4, 4, 9, 2, 2, 5, 8, 3, 5, 1, 8, 8, 4, 1, 5, 6, 7, 7, 4, 7, 3,
        8, 9, 4, 8, 9, 4, 1, 4, 3, 6, 1, 2, 2, 2, 5]),
 array([6, 8, 4, 7, 7, 4, 7, 5, 6, 6, 1, 8, 4, 3, 4, 5, 6, 8, 8, 6, 7, 3,
        8, 3, 3, 7, 2, 9, 3, 9, 6, 2, 1, 3, 8, 7, 4, 6, 2, 8, 2, 7, 5, 3,
        9, 5, 5, 8, 5

In [4]:
population.individuals

[array([2, 4, 9, 4, 7, 1, 4, 3, 6, 1, 7, 7, 1, 8, 8, 4, 5, 7, 2, 1, 2, 4,
        4, 3, 8, 5, 3, 6, 9, 8, 9, 5, 7, 3, 8, 3, 5, 5, 7, 9, 4, 5, 3, 4,
        6, 6, 9, 6, 2, 5, 1, 3, 2, 6, 1, 6, 6, 8, 5, 9, 9, 8, 7, 7, 8, 6,
        5, 1, 9, 4, 2, 8, 3, 2, 7, 2, 1, 2, 3, 1, 9]),
 array([2, 1, 3, 5, 9, 6, 2, 5, 7, 8, 5, 6, 4, 6, 8, 8, 1, 6, 7, 9, 3, 3,
        2, 5, 8, 1, 7, 3, 8, 5, 8, 2, 4, 1, 4, 1, 7, 6, 5, 8, 1, 7, 3, 6,
        7, 1, 2, 9, 2, 8, 4, 3, 9, 2, 4, 7, 2, 4, 1, 5, 4, 7, 5, 6, 5, 7,
        6, 9, 9, 4, 3, 9, 9, 8, 6, 4, 9, 3, 2, 3, 1]),
 array([8, 7, 7, 1, 6, 3, 6, 1, 3, 1, 5, 8, 9, 2, 7, 5, 3, 8, 9, 7, 7, 4,
        3, 2, 5, 6, 8, 6, 3, 9, 4, 8, 2, 8, 7, 8, 6, 4, 1, 5, 4, 9, 2, 6,
        6, 9, 2, 5, 9, 8, 5, 7, 2, 4, 4, 9, 9, 5, 7, 2, 1, 3, 5, 3, 6, 5,
        3, 3, 1, 7, 6, 1, 1, 2, 4, 8, 1, 2, 4, 9, 4]),
 array([1, 3, 9, 7, 5, 1, 1, 7, 7, 5, 9, 8, 1, 3, 2, 6, 2, 6, 4, 1, 7, 7,
        8, 2, 3, 1, 6, 6, 6, 5, 5, 6, 4, 3, 3, 8, 2, 8, 4, 3, 5, 4, 8, 2,
        7, 6, 9, 9, 7

In [9]:
np.array(population.individuals)

array([[3, 8, 8, 4, 1, 4, 7, 4, 6, 3, 5, 7, 9, 8, 5, 2, 2, 3, 7, 9, 6, 5,
        3, 3, 2, 3, 6, 4, 6, 5, 1, 4, 5, 8, 1, 9, 4, 8, 6, 7, 7, 5, 4, 6,
        1, 4, 6, 6, 9, 9, 2, 5, 7, 3, 8, 7, 8, 3, 6, 9, 1, 7, 5, 8, 7, 9,
        2, 2, 3, 1, 2, 9, 4, 5, 2, 1, 9, 1, 1, 8, 2],
       [8, 5, 5, 4, 2, 6, 3, 6, 1, 8, 4, 5, 6, 9, 1, 3, 7, 6, 1, 7, 7, 2,
        7, 3, 7, 9, 7, 9, 5, 9, 1, 7, 1, 3, 7, 2, 3, 1, 5, 2, 8, 3, 5, 3,
        5, 5, 4, 1, 6, 2, 6, 8, 8, 9, 6, 6, 2, 9, 9, 7, 1, 8, 6, 4, 4, 2,
        3, 4, 8, 8, 5, 3, 2, 4, 4, 2, 1, 8, 9, 9, 4],
       [6, 9, 1, 4, 4, 7, 4, 3, 3, 3, 1, 7, 3, 8, 2, 9, 3, 2, 5, 3, 4, 5,
        2, 6, 2, 8, 2, 2, 6, 5, 9, 2, 7, 1, 4, 8, 4, 5, 8, 5, 5, 8, 6, 1,
        9, 6, 1, 3, 2, 2, 7, 7, 1, 5, 1, 8, 9, 4, 5, 9, 7, 7, 4, 8, 9, 8,
        9, 1, 4, 6, 6, 3, 5, 6, 3, 7, 8, 1, 7, 9, 6],
       [8, 7, 9, 7, 9, 4, 6, 6, 1, 7, 2, 2, 8, 2, 3, 8, 5, 3, 7, 3, 6, 6,
        6, 1, 9, 4, 7, 7, 1, 4, 2, 4, 9, 8, 2, 1, 7, 6, 4, 8, 7, 5, 6, 3,
        3, 4, 3, 1, 3, 5

In [16]:
num_parents = int(len(population)/2)
num_parents

5

In [21]:
np.random.choice(10, size=(num_parents, 2), replace=True)

array([[3, 2],
       [5, 8],
       [0, 3],
       [3, 7],
       [4, 6]])

In [28]:
np.random.randint(rows, size=int(num_parents/2))

array([5, 8, 5, 0, 7])

In [30]:
parent_indices[:, 0]

array([5, 3, 8, 4, 6])

In [40]:
slices = [slice(0, 5), slice(0, 6), slice(0, 7)]


population_array[[1,2,3]][:, :5]

array([[7, 3, 3, 3, 8],
       [1, 7, 5, 5, 9],
       [6, 6, 3, 8, 6]])

In [43]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3, 4, 5, 6, 7],
                [8, 9, 10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19, 20, 21],
                [22, 23, 24, 25, 26, 27, 28],
                [29, 30, 31, 32, 33, 34, 35]])

# Indices to slice
indices = [1, 2, 3]
slices = [slice(None, 5), slice(None, 6), slice(None, 7)]

# Slice the array
sliced_arr = arr[indices][:, slices]

print(sliced_arr)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
np.concatenate((population_array[parent1_indices, :crossover_points, :],
                                population_array[parent2_indices, crossover_points:, :]), axis=1)

In [ ]:
population_array[parent1_indices, :crossover_points]

In [48]:
crossover_points

array([ 9, 10,  7,  0,  4])

In [54]:
population_array[parent1_indices][:, [[1,2,3], [3,4], [1,2], [3,4]]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [71]:
population_array[parent1_indices]

array([[1, 7, 5, 5, 9, 5, 8, 2, 2, 6, 6, 7, 5, 4, 4, 1, 3, 9, 1, 8, 3, 4,
        7, 8, 4, 2, 3, 1, 6, 9, 8, 8, 6, 8, 5, 8, 5, 1, 3, 7, 9, 9, 9, 3,
        6, 6, 6, 5, 4, 2, 5, 7, 5, 9, 1, 2, 3, 4, 7, 9, 3, 7, 6, 3, 4, 7,
        2, 6, 1, 4, 2, 2, 1, 9, 4, 8, 7, 3, 2, 1, 8],
       [4, 9, 8, 6, 6, 7, 4, 1, 3, 8, 8, 2, 5, 6, 2, 5, 8, 4, 6, 3, 1, 7,
        2, 5, 3, 2, 5, 9, 7, 1, 1, 8, 9, 7, 7, 6, 9, 5, 4, 5, 2, 8, 8, 5,
        4, 3, 9, 7, 7, 3, 4, 4, 3, 6, 9, 6, 1, 1, 2, 1, 9, 8, 2, 5, 4, 7,
        1, 2, 7, 3, 9, 1, 6, 2, 5, 4, 6, 9, 3, 3, 8],
       [8, 7, 7, 4, 3, 2, 1, 9, 1, 1, 4, 3, 5, 2, 5, 9, 2, 2, 8, 1, 3, 5,
        6, 3, 2, 6, 1, 9, 8, 4, 4, 9, 7, 4, 9, 5, 7, 4, 2, 1, 2, 6, 2, 8,
        7, 7, 9, 9, 5, 2, 8, 9, 3, 5, 7, 3, 7, 6, 6, 3, 6, 6, 1, 6, 9, 5,
        8, 5, 1, 6, 3, 8, 3, 8, 1, 7, 4, 4, 8, 4, 5],
       [6, 5, 1, 9, 9, 8, 2, 6, 4, 8, 7, 9, 4, 8, 3, 4, 1, 2, 4, 8, 7, 1,
        5, 2, 3, 4, 6, 6, 2, 8, 2, 6, 5, 6, 1, 4, 7, 2, 7, 5, 1, 5, 5, 8,
        5, 3, 8, 2, 2, 9

In [64]:
np.arange(crossover_points.reshape( -1, 1))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
a = np.ma.masked_array(population_array[parent1_indices], row_masks)
a.filled(0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 5, 4, 2, 5, 7, 5, 9, 1, 2, 3, 4, 7, 9, 3, 7, 6, 3, 4, 7,
        2, 6, 1, 4, 2, 2, 1, 9, 4, 8, 7, 3, 2, 1, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5,
        4, 3, 9, 7, 7, 3, 4, 4, 3, 6, 9, 6, 1, 1, 2, 1, 9, 8, 2, 5, 4, 7,
        1, 2, 7, 3, 9, 1, 6, 2, 5, 4, 6, 9, 3, 3, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 9, 9, 5, 2, 8, 9, 3, 5, 7, 3, 7, 6, 6, 3, 6, 6, 1, 6, 9, 5,
        8, 5, 1, 6, 3, 8, 3, 8, 1, 7, 4, 4, 8, 4, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0

In [78]:
# Create row masks for each crossover point
row_masks = np.arange(cols) > crossover_points[:, np.newaxis]

row_masks

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
     

In [70]:
rows

11

In [69]:
row_masks.shape

(5, 81)

In [66]:
np.newaxis

In [83]:
cols

81

In [82]:
np.random.randint(cols)

0

In [91]:
population.individuals

AttributeError: 'list' object has no attribute 'dtype'

In [31]:
prob = 0.5

sum(np.random.choice([0,1], size = int(num_parents/2), replace=True, p=[1-prob, prob]))

3

In [34]:
np.setdiff1d(np.arange(num_parents), parent_indices.flatten())

array([8])

In [27]:
population_array = np.array(population)
    
# Get the number of parents and the shape of each parent
num_parents = len(population)
rows, cols = population_array.shape

# Select two random parents for each offspring without replacement
parent_indices = np.random.choice(num_parents, size=(int(num_parents/2), 2), replace=False)

parent_indices

# Choose random crossover points for each pair of parents
crossover_points = np.random.randint(cols-1, size=int(num_parents/2))

# Matrices with parents from both sides
parent1 = population_array[parent_indices[:, 0]]
parent2 = population_array[parent_indices[:, 1]]

# Mask all the values that are above/below crossover line with zeros
parent1_masked = np.ma.masked_array(parent1, np.arange(cols) > crossover_points[:, np.newaxis]).filled(0)
parent2_masked = np.ma.masked_array(parent2, np.arange(cols) <= crossover_points[:, np.newaxis]).filled(0)

# offsprings are just sum of parents
offspring1 = parent1_masked + parent2_masked
offspring2 = (parent1 - parent1_masked) + (parent2 - parent2_masked)

offspring = np.concatenate((offspring1, offspring2))

if offspring.shape[0] < num_parents:
    # Append random offspring from parents if we have smaller offspring size than population size
    while offspring.shape[0] < num_parents:
        offspring = np.append(offspring, 
                            np.expand_dims(population_array[np.random.choice(len(population_array))], axis=0), axis = 0)

offspring

# return offspring.tolist()

array([[2, 1, 3, 5, 9, 6, 2, 5, 7, 8, 5, 6, 4, 6, 8, 8, 1, 6, 7, 9, 3, 3,
        2, 5, 5, 6, 8, 6, 3, 9, 4, 8, 2, 8, 7, 8, 6, 4, 1, 5, 4, 9, 2, 6,
        6, 9, 2, 5, 9, 8, 5, 7, 2, 4, 4, 9, 9, 5, 7, 2, 1, 3, 5, 3, 6, 5,
        3, 3, 1, 7, 6, 1, 1, 2, 4, 8, 1, 2, 4, 9, 4],
       [7, 1, 1, 4, 5, 1, 7, 6, 4, 8, 6, 8, 6, 6, 4, 7, 7, 9, 8, 2, 7, 5,
        8, 7, 9, 3, 5, 8, 2, 6, 1, 6, 1, 2, 6, 5, 3, 9, 9, 5, 8, 9, 1, 8,
        3, 5, 5, 2, 4, 3, 5, 4, 6, 9, 8, 5, 2, 8, 4, 2, 3, 7, 4, 3, 3, 2,
        3, 7, 5, 2, 7, 2, 5, 1, 4, 3, 1, 9, 9, 9, 4],
       [3, 5, 1, 9, 5, 6, 6, 6, 5, 8, 2, 8, 1, 8, 6, 7, 9, 3, 8, 8, 5, 5,
        1, 1, 2, 9, 1, 1, 4, 9, 8, 7, 3, 2, 5, 2, 5, 2, 3, 4, 6, 4, 7, 1,
        3, 3, 8, 4, 8, 1, 4, 9, 6, 7, 9, 7, 7, 3, 5, 6, 2, 6, 2, 7, 3, 6,
        7, 4, 7, 9, 9, 8, 3, 5, 9, 1, 2, 4, 2, 5, 8],
       [3, 4, 5, 9, 3, 3, 6, 9, 1, 3, 6, 9, 4, 1, 1, 1, 1, 5, 5, 6, 1, 8,
        7, 3, 7, 6, 2, 1, 9, 2, 4, 6, 9, 2, 2, 9, 4, 4, 5, 7, 5, 2, 4, 1,
        9, 2, 4, 4, 8, 2

In [26]:
np.append(offspring, 
        np.expand_dims(population_array[np.random.choice(len(population_array))], axis=0), axis = 0).shape

(11, 81)

In [20]:
population_array[np.random.choice(len(population_array))]

array([1, 2, 2, 5, 1, 5, 5, 3, 9, 5, 6, 6, 8, 4, 9, 9, 3, 8, 4, 5, 7, 6,
       8, 2, 2, 7, 8, 3, 3, 7, 4, 6, 5, 9, 4, 9, 2, 3, 3, 8, 7, 7, 3, 1,
       9, 2, 4, 4, 8, 2, 4, 7, 1, 7, 8, 9, 6, 4, 6, 1, 9, 6, 8, 7, 1, 4,
       5, 1, 2, 1, 5, 2, 7, 5, 3, 8, 9, 1, 6, 3, 6])

In [18]:
offspring

array([[2, 1, 3, 5, 6, 3, 6, 1, 3, 1, 5, 8, 9, 2, 7, 5, 3, 8, 9, 7, 7, 4,
        3, 2, 5, 6, 8, 6, 3, 9, 4, 8, 2, 8, 7, 8, 6, 4, 1, 5, 4, 9, 2, 6,
        6, 9, 2, 5, 9, 8, 5, 7, 2, 4, 4, 9, 9, 5, 7, 2, 1, 3, 5, 3, 6, 5,
        3, 3, 1, 7, 6, 1, 1, 2, 4, 8, 1, 2, 4, 9, 4],
       [1, 2, 2, 5, 1, 5, 5, 3, 9, 5, 6, 6, 8, 4, 9, 9, 3, 8, 4, 5, 7, 6,
        8, 2, 2, 7, 8, 3, 4, 9, 8, 7, 3, 2, 5, 2, 5, 2, 3, 4, 6, 4, 7, 1,
        3, 3, 8, 4, 8, 1, 4, 9, 6, 7, 9, 7, 7, 3, 5, 6, 2, 6, 2, 7, 3, 6,
        7, 4, 7, 9, 9, 8, 3, 5, 9, 1, 2, 4, 2, 4, 4],
       [2, 8, 9, 4, 6, 8, 1, 9, 3, 8, 6, 2, 5, 3, 3, 6, 3, 8, 1, 4, 5, 8,
        4, 2, 6, 9, 7, 2, 7, 9, 8, 9, 9, 1, 7, 3, 5, 1, 9, 4, 9, 6, 2, 1,
        1, 1, 2, 4, 5, 1, 7, 6, 3, 8, 8, 5, 1, 7, 2, 9, 7, 5, 3, 9, 2, 3,
        7, 1, 9, 8, 7, 8, 7, 6, 5, 6, 4, 1, 4, 5, 8],
       [8, 4, 3, 2, 4, 1, 4, 8, 7, 2, 9, 6, 1, 1, 6, 5, 8, 7, 2, 1, 2, 4,
        4, 3, 8, 5, 3, 6, 9, 8, 9, 5, 7, 3, 8, 3, 5, 5, 7, 9, 4, 5, 3, 4,
        6, 6, 9, 6, 2, 5

In [13]:
np.concatenate((offspring1, offspring2)).shape

(10, 81)

In [11]:
offspring1

array([[2, 1, 3, 5, 9, 6, 2, 5, 7, 8, 5, 6, 4, 6, 8, 8, 1, 6, 7, 9, 3, 3,
        2, 5, 8, 1, 7, 3, 8, 5, 8, 2, 4, 1, 4, 1, 7, 6, 5, 8, 1, 7, 3, 6,
        7, 1, 2, 9, 2, 8, 4, 3, 9, 2, 4, 7, 2, 4, 1, 5, 4, 7, 5, 6, 5, 7,
        6, 9, 9, 4, 3, 9, 9, 8, 6, 4, 9, 3, 2, 9, 4],
       [2, 8, 9, 4, 6, 8, 1, 9, 3, 8, 6, 2, 5, 3, 3, 6, 3, 8, 1, 4, 5, 8,
        4, 2, 6, 9, 7, 2, 7, 9, 8, 9, 9, 1, 7, 3, 3, 7, 8, 6, 1, 7, 4, 1,
        9, 1, 2, 2, 2, 1, 5, 4, 5, 7, 8, 3, 5, 8, 2, 4, 3, 7, 9, 3, 5, 4,
        7, 9, 5, 1, 4, 6, 7, 7, 9, 4, 2, 9, 1, 6, 2],
       [8, 4, 3, 2, 4, 1, 4, 8, 7, 2, 9, 6, 1, 1, 6, 5, 8, 7, 6, 4, 9, 4,
        9, 3, 6, 7, 1, 3, 3, 5, 6, 2, 6, 7, 6, 8, 5, 1, 9, 4, 9, 6, 2, 1,
        1, 1, 2, 4, 5, 1, 7, 6, 3, 8, 8, 5, 1, 7, 2, 9, 7, 5, 3, 9, 2, 3,
        7, 1, 9, 8, 7, 8, 7, 6, 5, 6, 4, 1, 4, 5, 8],
       [2, 4, 9, 4, 7, 1, 4, 3, 6, 1, 7, 7, 1, 8, 8, 4, 5, 7, 2, 1, 2, 4,
        4, 3, 8, 5, 3, 6, 9, 8, 9, 5, 7, 3, 8, 3, 5, 5, 7, 9, 4, 5, 3, 4,
        6, 6, 9, 6, 2, 5

In [9]:
population_array[np.random.choice(len(population_array))]

array([5, 2, 3, 8, 9, 4, 4, 4, 2, 3, 2, 8, 5, 2, 7, 9, 3, 8, 6, 4, 9, 4,
       9, 3, 6, 7, 1, 3, 3, 5, 6, 2, 6, 7, 6, 8, 5, 1, 9, 4, 9, 6, 2, 1,
       1, 1, 2, 4, 5, 1, 7, 6, 3, 8, 8, 5, 1, 7, 2, 9, 7, 5, 3, 9, 2, 3,
       7, 1, 9, 8, 7, 8, 7, 6, 5, 6, 4, 1, 4, 5, 8])

In [10]:
np.append(offspring, population_array[np.random.choice(len(population_array))])

array([2, 1, 3, 5, 9, 6, 2, 5, 7, 8, 5, 6, 4, 6, 8, 8, 1, 6, 7, 9, 3, 3,
       2, 5, 8, 1, 7, 3, 8, 5, 8, 2, 4, 1, 4, 1, 7, 6, 5, 8, 1, 7, 3, 6,
       7, 1, 2, 9, 2, 8, 4, 3, 9, 2, 4, 7, 2, 4, 1, 5, 4, 7, 5, 6, 5, 7,
       6, 9, 9, 4, 3, 9, 9, 8, 6, 4, 9, 3, 2, 9, 4, 2, 8, 9, 4, 6, 8, 1,
       9, 3, 8, 6, 2, 5, 3, 3, 6, 3, 8, 1, 4, 5, 8, 4, 2, 6, 9, 7, 2, 7,
       9, 8, 9, 9, 1, 7, 3, 3, 7, 8, 6, 1, 7, 4, 1, 9, 1, 2, 2, 2, 1, 5,
       4, 5, 7, 8, 3, 5, 8, 2, 4, 3, 7, 9, 3, 5, 4, 7, 9, 5, 1, 4, 6, 7,
       7, 9, 4, 2, 9, 1, 6, 2, 8, 4, 3, 2, 4, 1, 4, 8, 7, 2, 9, 6, 1, 1,
       6, 5, 8, 7, 6, 4, 9, 4, 9, 3, 6, 7, 1, 3, 3, 5, 6, 2, 6, 7, 6, 8,
       5, 1, 9, 4, 9, 6, 2, 1, 1, 1, 2, 4, 5, 1, 7, 6, 3, 8, 8, 5, 1, 7,
       2, 9, 7, 5, 3, 9, 2, 3, 7, 1, 9, 8, 7, 8, 7, 6, 5, 6, 4, 1, 4, 5,
       8, 2, 4, 9, 4, 7, 1, 4, 3, 6, 1, 7, 7, 1, 8, 8, 4, 5, 7, 2, 1, 2,
       4, 4, 3, 8, 5, 3, 6, 9, 8, 9, 5, 7, 3, 8, 3, 5, 5, 7, 9, 4, 5, 3,
       4, 6, 6, 9, 6, 2, 5, 1, 3, 2, 6, 1, 6, 6, 8,

In [84]:
b = np.ma.masked_array(population_array[parent1_indices], np.arange(cols) <= crossover_points[:, np.newaxis]).filled(0)

In [85]:
a = np.ma.masked_array(population_array[parent1_indices], np.arange(cols) > crossover_points[:, np.newaxis]).filled(0)

In [87]:
a + b

array([[1, 7, 5, 5, 9, 5, 8, 2, 2, 6, 6, 7, 5, 4, 4, 1, 3, 9, 1, 8, 3, 4,
        7, 8, 4, 2, 3, 1, 6, 9, 8, 8, 6, 8, 5, 8, 5, 1, 3, 7, 9, 9, 9, 3,
        6, 6, 6, 5, 4, 2, 5, 7, 5, 9, 1, 2, 3, 4, 7, 9, 3, 7, 6, 3, 4, 7,
        2, 6, 1, 4, 2, 2, 1, 9, 4, 8, 7, 3, 2, 1, 8],
       [4, 9, 8, 6, 6, 7, 4, 1, 3, 8, 8, 2, 5, 6, 2, 5, 8, 4, 6, 3, 1, 7,
        2, 5, 3, 2, 5, 9, 7, 1, 1, 8, 9, 7, 7, 6, 9, 5, 4, 5, 2, 8, 8, 5,
        4, 3, 9, 7, 7, 3, 4, 4, 3, 6, 9, 6, 1, 1, 2, 1, 9, 8, 2, 5, 4, 7,
        1, 2, 7, 3, 9, 1, 6, 2, 5, 4, 6, 9, 3, 3, 8],
       [8, 7, 7, 4, 3, 2, 1, 9, 1, 1, 4, 3, 5, 2, 5, 9, 2, 2, 8, 1, 3, 5,
        6, 3, 2, 6, 1, 9, 8, 4, 4, 9, 7, 4, 9, 5, 7, 4, 2, 1, 2, 6, 2, 8,
        7, 7, 9, 9, 5, 2, 8, 9, 3, 5, 7, 3, 7, 6, 6, 3, 6, 6, 1, 6, 9, 5,
        8, 5, 1, 6, 3, 8, 3, 8, 1, 7, 4, 4, 8, 4, 5],
       [6, 5, 1, 9, 9, 8, 2, 6, 4, 8, 7, 9, 4, 8, 3, 4, 1, 2, 4, 8, 7, 1,
        5, 2, 3, 4, 6, 6, 2, 8, 2, 6, 5, 6, 1, 4, 7, 2, 7, 5, 1, 5, 5, 8,
        5, 3, 8, 2, 2, 9

In [79]:
np.ma.masked_array(population_array[parent1_indices], row_masks).filled(0)

array([[1, 7, 5, 5, 9, 5, 8, 2, 2, 6, 6, 7, 5, 4, 4, 1, 3, 9, 1, 8, 3, 4,
        7, 8, 4, 2, 3, 1, 6, 9, 8, 8, 6, 8, 5, 8, 5, 1, 3, 7, 9, 9, 9, 3,
        6, 6, 6, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 9, 8, 6, 6, 7, 4, 1, 3, 8, 8, 2, 5, 6, 2, 5, 8, 4, 6, 3, 1, 7,
        2, 5, 3, 2, 5, 9, 7, 1, 1, 8, 9, 7, 7, 6, 9, 5, 4, 5, 2, 8, 8, 5,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [8, 7, 7, 4, 3, 2, 1, 9, 1, 1, 4, 3, 5, 2, 5, 9, 2, 2, 8, 1, 3, 5,
        6, 3, 2, 6, 1, 9, 8, 4, 4, 9, 7, 4, 9, 5, 7, 4, 2, 1, 2, 6, 2, 8,
        7, 7, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 5, 1, 9, 9, 8, 2, 6, 4, 8, 7, 9, 4, 8, 3, 4, 1, 2, 4, 8, 7, 1,
        5, 2, 3, 4, 6, 6, 2, 8, 2, 6, 5, 6, 1, 4, 7, 2, 7, 5, 1, 5, 5, 8,
        5, 3, 8, 2, 2, 9

In [81]:
np.ma.masked_array(population_array[parent1_indices], np.arange(cols) > crossover_points[:, np.newaxis]).filled(0)

array([[1, 7, 5, 5, 9, 5, 8, 2, 2, 6, 6, 7, 5, 4, 4, 1, 3, 9, 1, 8, 3, 4,
        7, 8, 4, 2, 3, 1, 6, 9, 8, 8, 6, 8, 5, 8, 5, 1, 3, 7, 9, 9, 9, 3,
        6, 6, 6, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 9, 8, 6, 6, 7, 4, 1, 3, 8, 8, 2, 5, 6, 2, 5, 8, 4, 6, 3, 1, 7,
        2, 5, 3, 2, 5, 9, 7, 1, 1, 8, 9, 7, 7, 6, 9, 5, 4, 5, 2, 8, 8, 5,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [8, 7, 7, 4, 3, 2, 1, 9, 1, 1, 4, 3, 5, 2, 5, 9, 2, 2, 8, 1, 3, 5,
        6, 3, 2, 6, 1, 9, 8, 4, 4, 9, 7, 4, 9, 5, 7, 4, 2, 1, 2, 6, 2, 8,
        7, 7, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 5, 1, 9, 9, 8, 2, 6, 4, 8, 7, 9, 4, 8, 3, 4, 1, 2, 4, 8, 7, 1,
        5, 2, 3, 4, 6, 6, 2, 8, 2, 6, 5, 6, 1, 4, 7, 2, 7, 5, 1, 5, 5, 8,
        5, 3, 8, 2, 2, 9

In [66]:
array = np.stack(population)

array.reshape(array.shape[0], -1)

AttributeError: module 'numpy' has no attribute 'unstack'

In [ ]:
def single_point_crossover(population):
    """
    Perform single-point crossover on a population of parent matrices.
    
    Args:
        population (list): A list of parent matrices (numpy.ndarray).
        
    Returns:
        list: A list of offspring matrices.
    """
    # Convert the population to a single 3D array
    population_array = np.stack(population)
    
    # Get the number of parents and the shape of each parent
    num_parents = len(population)
    rows, cols = population_array.shape[1:]
    
    # Select two random parents for each offspring
    parent_indices = np.random.choice(num_parents, size=(num_parents, 2), replace=True)
    
    # Choose random crossover points along the rows
    crossover_points = np.random.randint(rows, size=num_parents)
    
    # Create the offspring matrices using advanced indexing and broadcasting
    parent1_indices = parent_indices[:, 0]
    parent2_indices = parent_indices[:, 1]
    
    offspring1 = np.concatenate((population_array[parent1_indices, :crossover_points, :],
                                 population_array[parent2_indices, crossover_points:, :]), axis=1)
    
    offspring2 = np.concatenate((population_array[parent2_indices, :crossover_points, :],
                                 population_array[parent1_indices, crossover_points:, :]), axis=1)
    
    offspring = np.concatenate((offspring1, offspring2), axis=0)
    
    return offspring.tolist()

In [37]:
population.selection('roulette')
[ i.fitness for i in population.individuals]


[84, 82, 83, 81, 84, 77, 83, 84, 79, 71]

In [20]:
individual

[[8 8 1 7 3 2 9 6 6]
 [4 2 2 4 5 6 5 2 3]
 [1 1 8 1 5 5 4 8 7]
 [6 3 7 5 6 2 4 1 7]
 [7 7 6 9 9 6 9 9 3]
 [5 9 8 9 3 9 1 3 3]
 [3 7 6 9 2 7 8 2 1]
 [4 7 5 4 8 3 6 4 1]
 [8 2 8 5 5 4 2 4 1]]

In [13]:
num_iterations = 10000
current_best = individual
best_fitness = current_best.fitness

for i in range(num_iterations):
    # Generate neighbours
    neighbours = current_best.get_neighbours(number_of_neighbours=100, swap_number=1)
    # Best fitness 
    neighbours_fitness = [neighbour.fitness for neighbour in neighbours]
    best_neighbour = neighbours[np.argmin(neighbours_fitness)]

    if best_neighbour.fitness <= best_fitness:
        print(f'Iteration {i} - New best fitness: {best_neighbour.fitness}')
        current_best = best_neighbour
        best_fitness = best_neighbour.fitness

    if best_fitness == 0:
        print(f'Solution found at iteration {i}')
        break

print(f'Best fitness: {best_fitness}')

Iteration 0 - New best fitness: 38
Iteration 1 - New best fitness: 36
Iteration 2 - New best fitness: 34
Iteration 3 - New best fitness: 32
Iteration 4 - New best fitness: 31
Iteration 5 - New best fitness: 30
Iteration 6 - New best fitness: 29
Iteration 7 - New best fitness: 28
Iteration 8 - New best fitness: 27
Iteration 9 - New best fitness: 27
Iteration 10 - New best fitness: 27
Iteration 11 - New best fitness: 27
Iteration 12 - New best fitness: 27
Iteration 13 - New best fitness: 27
Iteration 14 - New best fitness: 27
Iteration 15 - New best fitness: 27
Iteration 16 - New best fitness: 27
Iteration 17 - New best fitness: 27
Iteration 18 - New best fitness: 27
Iteration 19 - New best fitness: 27
Iteration 20 - New best fitness: 27
Iteration 21 - New best fitness: 27
Iteration 22 - New best fitness: 27
Iteration 23 - New best fitness: 27
Iteration 24 - New best fitness: 27
Iteration 25 - New best fitness: 27
Iteration 26 - New best fitness: 27
Iteration 27 - New best fitness: 27
It

KeyboardInterrupt: 

In [8]:
best_neighbour

[[9 4 7 3 2 6 5 8 1]
 [2 5 6 1 8 7 9 4 3]
 [8 3 1 9 4 5 6 2 7]
 [4 7 3 5 9 2 1 6 8]
 [1 2 9 8 6 4 7 3 5]
 [5 6 8 7 1 3 4 9 2]
 [7 9 2 4 5 8 3 1 6]
 [6 1 5 2 3 9 8 7 4]
 [3 8 4 6 7 1 2 5 9]]